# Generated by Django 4.2 on 2023-04-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.user'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post',
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('PostCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Post',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
    ]
