# Generated by Django 4.2 on 2023-04-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_comment_alter_author_author_remove_post_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('re', 'читатель-пользователь'), ('no', 'неавторизованный пользователь'), ('ne', 'новость'), ('po', 'статья')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
