# Generated by Django 4.2 on 2023-04-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_post_position_remove_user_position_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Post',
        ),
        migrations.AlterField(
            model_name='author',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
    ]
